### ISSUE TITLE
The default <{strong,b}> style doesn't actually bold the text.

### ISSUE THREAD

**Issue by marshallswain** [bitovi/documentjs#158]
The current style for `<b>` and `<strong>` is as follows:
```css
b, strong {
  font-weight: bolder;
}
```

This is not currently producing bold text:
![no-bold](https://cloud.githubusercontent.com/assets/128857/7693681/5e5c00ba-fd92-11e4-8f79-941096da7e7c.jpg)

Changing the font-weight attribute to 600 or above fixes the style:
```css
b, strong {
  font-weight: 900;
}
```
![900](https://cloud.githubusercontent.com/assets/128857/7693696/ba280a92-fd92-11e4-8f4f-2d4677f0aea2.jpg)
