### ISSUE TITLE
Optional parameters should be marked as optional

### ISSUE THREAD

**Issue by dispatchrabbi** [bitovi/documentjs#30]
This is how an optional `@param` is represented now:

``` html
<h4>timeout <code>{Number}</code></h4>
```

Here's how it should be:

``` html
<h4>timeout <code>{Number}</code><span class="optional">Optional</span></h4>
```

Along with this CSS:

``` css
.parameter .optional {
    float: right;
    font-size: 8pt;
    line-height: 20px;
}
```
